authors:
  jarriagadac:
    name: Juan P. Arriagada C.
    description: Exalumno de Ingeniería Civil Informática, apasionado por la tecnología y la educación. Actualmente trabajando en proyectos de software y compartiendo conocimientos con la comunidad.
    avatar: https://avatars.githubusercontent.com/u/7169909?v=4
    slug: jarriagadac
    url: https://github.com/jarriagadac